### ISSUE TITLE
line 24 wp

### ISSUE THREAD

**Issue by Tech-no-logic-cat** [universalweb/Whitepaper#2]
The UW is built to be a viable & realistic replacement for the modern Web in every way and then some.

suggest
The UW is built to be a viable & realistic replacement for the modern Web in every aspect.

**Comment by tomekmarchi** [comment]
Needs an addition that elaborates on the fact of it not being just a replacement and introduces novel concepts that change both what the word "Web" means and how it works from the bottom up. The WP regardless must be updated to reflect the new designs. It's outdated and due for a refresh once new specs are final.
